### PR TITLE
Fix empty user and leading slash on path edge cases.

### PR DESCRIPTION
**Pull request by jpoler**
@whilp

### CODE REVIEW

**Comment by whilp** [comment]
Thank you! I'd like to write some tests to validate this behavior. Can you describe the use case you have in mind (or input/output pairs)?

**Comment by whilp** [comment]
Curious what you think of https://github.com/whilp/git-urls/pull/4. That PR adds User to the other transports, where it was not previously set. I think that produces consistent, expected results, but I'd like to make sure it captures your use case.

**Comment by jpoler** [comment]
The two edge cases can be expressed in one input into `Parse`: `example.com:/my/repo.git` -> `ssh://@example.com//my/repo.git`. Obviously the input is a little weird but since an error isn't raised I think it makes sense to account for them.

**Comment by jpoler** [comment]
As to #4, I'm not totally sure how to account for that. It seems like the underlying `url.URL` type should actually detect an empty user and omit the `@` in its `String()` method.

**Comment by jpoler** [comment]
@whilp In retrospect, I think that the `ssh://@<host>` case really doesn't matter. That makes this jive with your #4 branch a bit better too.

**Comment by whilp** [comment]
OK, I think I'm finally getting it. ;) After starting at this for a bit, I believe the current behavior is more broken than we thought originally: relative paths are being translated to absolute paths, and absolute paths (as you observed) are gaining an extra leading slash.

To fix both of these problems, I think we should simply set `u.Path = match[3]`. I'll put together a branch that does just this; I'd like to know if that suits your use case as well.

Thanks again for reporting this!

**Comment by whilp** [comment]
OK, my stab is over in https://github.com/whilp/git-urls/pull/9

**Comment by whilp** [comment]
Superseded by #9. Thanks again!

**Pull request closed without merging**
